version: "3.7"

services:

  caddy:
    image: "docker.io/hectormolinero/caddy:latest"
    restart: "on-failure:3"
    ports:
      - "8080:80/tcp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "public-alice:/var/www/html/alice/:ro"
      - "public-bob:/var/www/html/bob/:ro"
      - "public-dan:/var/www/html/dan/:ro"

  sftp:
    image: "docker.io/hectormolinero/sftp:latest"
    restart: "on-failure:3"
    ports:
      - "2222:22/tcp"
    environment:
      SFTP_USERS: |
        alice:::1000:1000:public,private
        bob:password:plain:1001:1001:public,private
        dan:$$5$$salt$$Gcm6FsVtF/Qa77ZKD.iwsJlCVPY0XSMgLJL0Hnww/c1:encrypted:1002:1002:public,private
    volumes:
      - "./keys/host_ed25519.pem:/etc/ssh/ssh_host_ed25519_key"
      - "./keys/host_ed25519.pub:/etc/ssh/ssh_host_ed25519_key.pub"
      - "./keys/host_rsa.pem:/etc/ssh/ssh_host_rsa_key"
      - "./keys/host_rsa.pub:/etc/ssh/ssh_host_rsa_key.pub"
      - "./keys/alice_ed25519.pub:/home/alice/.ssh/authorized_keys.d/alice_ed25519.pub"
      - "public-alice:/home/alice/data/public/"
      - "private-alice:/home/alice/data/private/"
      - "public-bob:/home/bob/data/public/"
      - "private-bob:/home/bob/data/private/"
      - "public-dan:/home/dan/data/public/"
      - "private-dan:/home/dan/data/private/"

volumes:

  public-alice:
  private-alice:
  public-bob:
  private-bob:
  public-dan:
  private-dan:
